# Generated by Django 3.2.5 on 2021-09-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=15)),
                ('strap', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('link', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
    ]
